# Generated by Django 5.2.4 on 2025-07-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_passenger_booking_passenger_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
